#!/usr/bin/env python
"""Discover symbolic alpha formulas from cross-sectional features.

Numerai-style setup: given a panel of stock features {x_1, ..., x_d}
and a target return y, find a sparse symbolic expression  alpha(x)
that predicts y.  In the WorldQuant 101 tradition, alphas are short
formulas like  rank(x1) - rank(x2)*x3.

Here we keep it lean and use a polynomial grammar:
    Primitive ::= x_i  |  x_i * x_j  |  x_i^2  |  tanh(x_i)  |  rank(x_i)
and search for a sparse linear combination of these primitives.  This
mirrors the SINDy paradigm from Loop B of the paper, but on
cross-sectional financial features instead of PDE-derivative dictionaries.

Two variants are shown:
  (a) Discrete sparse regression  (STLSQ on the standardised dictionary).
  (b) Differentiable Gumbel-softmax sparse selection (Loop-A-style).

Output: discovered formula vs.\\ truth.

Usage:  python numerai_alpha.py
"""
from __future__ import annotations

import time
import numpy as np
import torch

torch.set_default_dtype(torch.float64)


# ----------------------------------------------------------------------
# Synthetic Numerai-like dataset.
# ----------------------------------------------------------------------

def make_data(n_samples=4000, n_features=5, noise=0.4, seed=0):
    """Return X (n,d), y (n,) where y is generated by a sparse polynomial
    of X plus heavy Gaussian noise (Numerai-style low-signal regime)."""
    rng = np.random.default_rng(seed)
    X = rng.standard_normal((n_samples, n_features))
    # True alpha (sparse polynomial): 0.6*x0 - 0.4*x1 + 0.3*x2*x3
    true = 0.6 * X[:, 0] - 0.4 * X[:, 1] + 0.3 * X[:, 2] * X[:, 3]
    y = true + noise * rng.standard_normal(n_samples)
    truth_terms = {"x0": 0.6, "x1": -0.4, "x0*x1": 0.0, "x2*x3": 0.3}
    return X, y, true, truth_terms


# ----------------------------------------------------------------------
# Build dictionary of candidate alpha primitives.
# ----------------------------------------------------------------------

def build_dictionary(X):
    """Return Theta (n, P) and the list of primitive names."""
    n, d = X.shape
    cols = []; names = []
    # 1. linear terms
    for i in range(d):
        cols.append(X[:, i]);          names.append(f"x{i}")
    # 2. squares
    for i in range(d):
        cols.append(X[:, i] ** 2);     names.append(f"x{i}^2")
    # 3. cross products (i < j)
    for i in range(d):
        for j in range(i + 1, d):
            cols.append(X[:, i] * X[:, j])
            names.append(f"x{i}*x{j}")
    # 4. tanh(x_i)  (mild nonlinearity)
    for i in range(d):
        cols.append(np.tanh(X[:, i])); names.append(f"tanh(x{i})")
    # 5. rank (cross-sectional rank in [-1,1])
    for i in range(d):
        rk = np.argsort(np.argsort(X[:, i])) / max(n - 1, 1)
        cols.append(2 * rk - 1.0)
        names.append(f"rank(x{i})")
    Theta = np.stack(cols, axis=1)
    return Theta, names


# ----------------------------------------------------------------------
# (a) Discrete STLSQ on standardised dictionary.
# ----------------------------------------------------------------------

def stlsq(Theta, y, threshold, max_iter=25):
    coeffs, *_ = np.linalg.lstsq(Theta, y, rcond=None)
    for _ in range(max_iter):
        small = np.abs(coeffs) < threshold
        if not np.any(~small):
            return coeffs
        coeffs[small] = 0.0
        keep = ~small
        sub, *_ = np.linalg.lstsq(Theta[:, keep], y, rcond=None)
        coeffs[keep] = sub
    return coeffs


def sparse_discovery(Theta, y, threshold=0.10):
    col_norms = np.linalg.norm(Theta, axis=0) + 1e-30
    y_norm = np.linalg.norm(y) + 1e-30
    Theta_s = Theta / col_norms
    y_s = y / y_norm
    c_s = stlsq(Theta_s.copy(), y_s, threshold)
    support = np.abs(c_s) > 0
    coeffs = np.zeros(Theta.shape[1])
    if np.any(support):
        sub, *_ = np.linalg.lstsq(Theta[:, support], y, rcond=None)
        coeffs[support] = sub
    return coeffs


# ----------------------------------------------------------------------
# (b) Differentiable Gumbel-softmax selection.
# ----------------------------------------------------------------------

def diff_select(Theta_np, y_np, n_epochs=2000, lr=0.05,
                tau_start=2.0, tau_end=0.05,
                lambda_g=0.04, seed=0):
    """Continuous subset selection via per-column relaxed Bernoulli gates.

    Each dictionary column p has a gate g_p in [0,1] (sigmoid of a logit),
    plus a coefficient beta_p.  Prediction is sum_p g_p * beta_p * x_p.
    An L1 penalty on the gates drives most to zero.  At convergence we
    threshold gates and keep the survivors.

    This is the right relaxation when the truth has multiple active terms
    (Gumbel-softmax would only pick one).
    """
    torch.manual_seed(seed)
    Theta = torch.tensor(Theta_np)
    y = torch.tensor(y_np)
    n, P = Theta.shape
    # standardise columns so gate penalties bite uniformly
    col_std = Theta.std(0) + 1e-12
    Theta_s = Theta / col_std
    eta = torch.full((P,), -1.0, requires_grad=True)   # gate logits (start "off")
    beta = torch.zeros(P, requires_grad=True)
    opt = torch.optim.Adam([eta, beta], lr=lr)
    for ep in range(n_epochs):
        t = ep / max(n_epochs - 1, 1)
        tau = tau_start * (tau_end / tau_start) ** t
        # relaxed Bernoulli gates (annealed sigmoid temperature)
        gates = torch.sigmoid(eta / tau)
        coefs_s = gates * beta
        pred = Theta_s @ coefs_s
        loss = ((pred - y) ** 2).mean()
        # L1 sparsity on the gates themselves
        sparsity = gates.sum()
        loss_total = loss + lambda_g * sparsity
        opt.zero_grad(); loss_total.backward(); opt.step()
    with torch.no_grad():
        gates_final = torch.sigmoid(eta / tau_end).numpy()
        coefs_s_final = gates_final * beta.detach().numpy()
        # de-standardise
        coefs_final = coefs_s_final / col_std.numpy()
    return gates_final, coefs_final


# ----------------------------------------------------------------------
# Driver
# ----------------------------------------------------------------------

def report(coeffs, names, truth_terms, threshold=0.05, label="STLSQ"):
    print(f"  [{label}] discovered:")
    sel = [(n, c) for n, c in zip(names, coeffs) if abs(c) > threshold]
    sel.sort(key=lambda nc: -abs(nc[1]))
    for n, c in sel:
        true_c = truth_terms.get(n, 0.0)
        mark = "*" if abs(true_c) > 1e-6 else " "
        print(f"      {mark} {n:12s} coef={c:+.3f}  (truth={true_c:+.2f})")
    # support recovery
    found = set(n for n, c in sel)
    needed = set(k for k, v in truth_terms.items() if abs(v) > 1e-6)
    rec = needed.issubset(found)
    extra = found - needed
    print(f"      support {'recovered' if rec else 'MISSED'} | spurious={len(extra)}\n")
    return rec, len(extra)


def main():
    print(">> Numerai-style alpha discovery\n", flush=True)
    print(f"   Synthetic dataset with hidden alpha:")
    print(f"       y = 0.6*x0 - 0.4*x1 + 0.3*x2*x3 + heavy noise\n", flush=True)

    rows = []
    for noise in [0.2, 0.5, 1.0]:
        X, y, true, truth = make_data(n_samples=4000, n_features=5,
                                       noise=noise, seed=0)
        Theta, names = build_dictionary(X)
        snr = np.std(true) / noise
        print(f"--- Noise σ_y = {noise:.2f}   (signal/noise ≈ {snr:.2f})")
        # Method (a): STLSQ
        t0 = time.perf_counter()
        coeffs_a = sparse_discovery(Theta, y, threshold=0.10)
        t_a = time.perf_counter() - t0
        rec_a, sp_a = report(coeffs_a, names, truth, label=f"STLSQ ({t_a:.2f}s)")
        # Method (b): differentiable Gumbel-softmax
        t0 = time.perf_counter()
        pi, coeffs_b = diff_select(Theta, y, n_epochs=1500)
        t_b = time.perf_counter() - t0
        rec_b, sp_b = report(coeffs_b, names, truth, label=f"BernGate ({t_b:.2f}s)")
        rows.append({"noise": noise, "snr": snr,
                     "stlsq_recovered": rec_a, "stlsq_spurious": sp_a,
                     "gumbel_recovered": rec_b, "gumbel_spurious": sp_b})

    print("Summary:")
    print("  noise   SNR    STLSQ          BernGate")
    for r in rows:
        a = "✓" if r["stlsq_recovered"] else "✗"
        b = "✓" if r["gumbel_recovered"] else "✗"
        print(f"  {r['noise']:.2f}    {r['snr']:.2f}   {a} +{r['stlsq_spurious']}sp     "
              f"{b} +{r['gumbel_spurious']}sp")


if __name__ == "__main__":
    main()
